#!/usr/bin/env bash
# Pre-edit hook: evidence/ is generated by `make evidence`; block hand edits (exit 2).
set -euo pipefail

if ! command -v jq > /dev/null 2>&1; then
  exit 0
fi

FILE_PATH="$(jq -r '.tool_input.file_path // empty' 2> /dev/null || true)"

case "$FILE_PATH" in
  */evidence/README.md)
    exit 0
    ;;
  */evidence/*)
    echo "Blocked: $FILE_PATH is generated. Run 'make evidence' and review the diff instead." >&2
    exit 2
    ;;
esac
